// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WheelTracker.Services;

#nullable disable

namespace WheelTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101192323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WheelTracker.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CloseFee")
                        .HasColumnType("REAL");

                    b.Property<double?>("ClosePrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("CloseQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloseTransType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditDebit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentSharePrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("DTE")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DaysHeld")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fees")
                        .HasColumnType("REAL");

                    b.Property<double?>("Moneyness")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Premium")
                        .HasColumnType("REAL");

                    b.Property<double?>("PriceAtOpen")
                        .HasColumnType("REAL");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RealizedGainLoss")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Strategy")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Strike")
                        .HasColumnType("REAL");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnrealizedGainLoss")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
